#!/bin/sh

FFMPEGD_HOST=${FFMPEGD_HOST:-ffmpegd}
FFMPEGD_PORT=${FFMPEGD_PORT:-3367}

cleanup() {
	err=$?

	kill ${pid} >/dev/null 2>&1

	trap '' EXIT INT TERM
	exit $err
}
sig_cleanup() {
	trap '' EXIT # some shells will call EXIT after the INT handler
	false        # sets $?
	cleanup
}
trap cleanup EXIT
trap sig_cleanup INT QUIT TERM

ffmpeg_exec() {
	echo "${@}"
	# tail -f /dev/null
}

ffmpeg_exec "${@}" | ncat --no-shutdown ${FFMPEGD_HOST} ${FFMPEGD_PORT} &
# ffmpeg_exec "${@}" | socat TCP:${FFMPEGD_HOST}:${FFMPEGD_PORT} -
pid=$!

wait ${pid}
